# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'JFrogArtifactory'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "*.*",
            "target": "azdevopsshobz-generic-local/upload/"
          }
        ]
      }
    failNoOp: true
    
- task: ArtifactoryGenericDownload@3
  inputs:
#       connection: 'BasicAuth-artifactory'
    artifactoryService: 'JFrogArtifactory'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "azdevopsshobz-generic-local/upload/*.*",
            "target": "/home/shobhit/Downloads/azdownload/"
          }
        ]
      }
    failNoOp: true
